credentials:
  usernames:
    admin:
      name: 'Administrador'
      password: 'senhaadmin'
    usuario:
      name: 'Usuário Padrão'
      password: 'senhapadrao'
cookie:
  name: 'leverage_cookie'
  key: 'CHAVE_SUPER_SECRETA_123'
  expiry_days: 30
preauthorized:
  emails: []
